### ISSUE TITLE
Everytime Error Response by Placing Outbound Call

### ISSUE THREAD

**Issue by Lucksmith369** [twilio-labs/plugin-flex-outbound-dialpad#30]
Hey Guys,

im looking for the Bug but i dont find it yet.
If you Place a outboundcall you got everytime a error but the call is Placed and everything is working fine.

The error cames from the Response in DialPadUtil.js Line 37-57

Unexpected end of input.

Do you know a solution?

**Comment by jhunter-twilio** [comment]
Hi @Lucksmith369 

I'm not sure I follow the issue, can you post a screenshot or what you're seeing?

**Comment by jhunter-twilio** [comment]
@Lucksmith369 is this still an issue?
