### ISSUE TITLE
Dialpad is not closing nor adding the outbound task on flex

### ISSUE THREAD

**Issue by shageevan** [twilio-labs/plugin-flex-outbound-dialpad#32]
When making an outbound call, I can dial the number and the phone can be answered on the other end but the dial pad stays on the screen without closing. Hold music is heard on the other end.

**Comment by jhunter-twilio** [comment]
Hi @shageevan 

It sounds like something is misconfigured. Is this happening on every call?

**Comment by shageevan** [comment]
Hi @jhunter-twilio, I configured everything as mentioned. It is happening on all outbound calls. I will share a video later today.

**Comment by jhunter-twilio** [comment]
It definitely sounds misconfigured

I'd recommend taking a clean checkout, ensuring all the SIDs are setup in the environment file correctly, in particular the sync service sid (it sounds like that specifically is missing), deploying the functions and deploying the asset as described in the instructions.

If it's still happening can you watch the console logs and the callStatusUpdateHandler function and look for errors

**Comment by shageevan** [comment]
Sure. I will check on this and revert later today.

**Comment by shageevan** [comment]
Done. Works now.
